backend:
  name: github
  branch: main
  repo: KoalbyMQP/Documentation

# These lines should *not* be indented
media_folder: "static/img" 
public_folder: "/img/" 

collections:
  - name: docs
    label: Documentation
    folder: docs
    identifier_field: title
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - name: id
        label: ID
        widget: string
      - name: title
        label: Title
        widget: string
      - name: sidebar_label
        label: Sidebar Label
        widget: string
        required: false
      - name: sidebar_position
        label: Sidebar Position
        widget: number
        required: false
      - name: body
        label: Content
        widget: markdown
      - name: tags
        label: Tags
        widget: list
        required: false