backend:
  name: github
  branch: main
  repo: KoalbyMQP/Documentation

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: docs
    label: Documentation
    folder: docs
    identifier_field: title
    extension: md
    create: true
    path: "{{folder}}/{{slug}}"
    fields:
      - name: folder
        label: Folder Path
        widget: folder-select
        hint: "Select a folder or leave empty for root level"
        required: false
      - name: id
        label: ID
        widget: string
        hint: "Unique identifier for the document (e.g., 'intro' or 'tutorial-basics/create-page')"
      - name: title
        label: Title
        widget: string
      - name: sidebar_label
        label: Sidebar Label
        widget: string
        required: false
      - name: sidebar_position
        label: Sidebar Position
        widget: number
        required: false
        value_type: int
      - name: body
        label: Content
        widget: markdown
      - name: tags
        label: Tags
        widget: list
        required: false

  - name: category
    label: Documentation Categories
    folder: docs
    create: true
    identifier_field: label
    format: json
    extension: json
    path: "{{slug}}/_category_"
    slug: "{{label}}"
    fields:
      - name: label
        label: Category Label
        widget: string
        hint: "This will be both the folder name and display name"
      - name: position
        label: Position
        widget: number
        value_type: int
        hint: "Order in the sidebar (lower numbers appear first)"
      - name: type
        label: Category Type
        widget: select
        options: ["generated-index", "doc"]
        default: "generated-index"
        hint: "Usually leave as generated-index"
      - name: id
        label: Document ID
        widget: string
        required: false
        hint: "Only needed if type is 'doc'"