backend:
  name: github
  branch: main
  repo: KoalbyMQP/Documentation

media_folder: "static/img"
public_folder: "/img/"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  # SECTION COLLECTION:
  # This collection lets editors create/manage sections (folders) inside the docs folder.
  - name: sections
    label: Documentation Sections
    folder: docs
    create: true
    format: json
    extension: json
    path: "{{label}}/_category_"
    fields:
      - name: label
        label: Section Name
        widget: string
        hint: "Name of the new section/folder – this will be the folder name"
        pattern: ['^[a-zA-Z0-9-]+$', "Only letters, numbers, and hyphens are allowed"]
      - name: position
        label: Position
        widget: number
        value_type: int
        hint: "Order in the sidebar (lower numbers first)"
      - name: link
        label: Link Settings
        widget: object
        fields:
          - name: type
            label: Type
            widget: select
            options: ["generated-index", "doc"]
            default: "generated-index"
            hint: "Keep as generated-index for auto-generating a category index."
          - name: title
            label: Generated Index Title
            widget: string
            hint: "This title appears on the generated index page as the main title of the page."
          - name: slug
            label: URL Slug
            widget: string
            required: true
            hint: "Provide a URL-friendly string starting with a slash (e.g., '/visions' or '/speech-recognition'). This will determine the page URL and sidebar entry."
          - name: description
            label: Description
            widget: string
            required: false
            default: ""
            hint: "A brief description for the category page."

  # PAGE COLLECTION:
  # This collection lets editors create Markdown pages. They can be placed in any folder.
  - name: pages
    label: Documentation Pages
    folder: docs
    create: true
    format: frontmatter
    extension: md
    nested:
      depth: 100
      summary: '{{title}}'
    # The final path is computed based on the "dirname" field and the URL-friendly "slug".
    path: "{{dirname}}/{{slug}}"
    fields:
      - name: dirname
        label: Section/Folder
        widget: string
        hint: "The folder path where this page should be created. For a page inside a section, enter the section's folder name (e.g., 'tutorial-basics'). Leave empty for a page in the root docs folder."
      - name: title
        label: Page Title
        widget: string
      - name: slug
        label: URL Slug
        widget: string
        pattern: ['^[a-zA-Z0-9-]+$', "Only letters, numbers, and hyphens are allowed"]
        hint: "The URL-friendly version of the title (e.g., 'deploy-your-site')"
      - name: sidebar_position
        label: Page Position
        widget: number
        required: false
        value_type: int
        hint: "Order within the section (lower numbers first)"
      - name: id
        label: Page ID
        widget: string
        hint: "Unique identifier (e.g., 'intro' or 'installation')"
      - name: description
        label: Description
        widget: string
        required: false
        hint: "Brief description of the page content"
      - name: tags
        label: Tags
        widget: list
        required: false
      - name: body
        label: Content
        widget: markdown