backend:
  name: github
  branch: main
  repo: KoalbyMQP/Documentation

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs/"
    create: true
    delete: true
    identifier_field: "id"
    slug: "{{slug}}"
    path: "{{slug}}/index"
    editor:
      preview: false
    nested:
      depth: 100  # Allow infinite nesting
    filter:
      field: "folder"
      value: "docs"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Folder", name: "folder", widget: "hidden", default: "docs"}
      - {label: "Position", name: "sidebar_position", widget: "number", default: 0}
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "link", "quote", "code", "bulleted-list", "numbered-list"]
        editorComponents: ["image"]
        modes: ["rich_text"]
        hint: "Start with ## Section Heading for sub-sections"
    
  - name: "sections"
    label: "Sections"
    label_singular: "Section"
    folder: "docs/"
    create: true
    delete: true
    identifier_field: "id"
    slug: "{{slug}}"
    path: "{{slug}}/_category_"
    editor:
      preview: false
    fields:
      - {label: "Section Title", name: "label", widget: "string"}
      - {label: "Position", name: "position", widget: "number", default: 0}
      - {label: "Collapsible", name: "collapsed", widget: "boolean", default: false}
      - {label: "Folder Name", name: "id", widget: "string", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Only lowercase letters, numbers, and hyphens"]}
      - {label: "Description", name: "description", widget: "text", required: false}