backend:
  name: github
  branch: main
  repo: KoalbyMQP/Documentation
  commit_messages:
    create: "docs: create {{collection}} '{{slug}}'"
    update: "docs: update {{collection}} '{{slug}}'"
    delete: "docs: delete {{collection}} '{{slug}}'"
    uploadMedia: "docs: upload media file '{{path}}'"
    deleteMedia: "docs: delete media file '{{path}}'"

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: categories
    label: Categories
    label_singular: "Category"
    folder: "docs/"
    create: true
    identifier_field: label
    format: json
    extension: json
    slug: "{{fields.slug}}/_category_"
    path: "{{fields.slug}}/_category_"
    fields:
      - {label: "Label", name: "label", widget: "string", pattern: ["^[a-z0-9- ]+$", "Only lowercase letters, numbers, spaces and dashes"]}
      - {label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Only lowercase letters, numbers and dashes"]}
      - {label: "Position", name: "position", widget: "number", value_type: "int"}
      - {
          label: "Parent Category",
          name: "parent",
          widget: "relation",
          collection: "categories",
          search_fields: ["label"],
          value_field: "label",
          required: false
        }
      - {
          label: "Category Type",
          name: "type",
          widget: "select",
          options: ["generated-index", "doc"],
          default: "generated-index"
        }

  - name: documents
    label: Documents
    label_singular: "Document"
    folder: "docs/"
    create: true
    extension: md
    format: frontmatter
    identifier_field: id
    path: "{{folder}}/{{slug}}"
    slug: "{{fields.slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Folder Path",
          name: "folder",
          widget: "folder-select",
          hint: "Select or create folder path (e.g. 'tutorial-basics')",
          default: ""
        }
      - {label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-/]+$", "Only lowercase letters, numbers, and dashes"]}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false}
      - {label: "Sidebar Position", name: "sidebar_position", widget: "number", value_type: "int", required: false}
      - {
          label: "Parent Category",
          name: "parent_category",
          widget: "relation",
          collection: "categories",
          search_fields: ["label"],
          value_field: "label",
          required: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}